# This contains common shell utilities used by all users
# This file is automatically generated and should not be modified
# If you want to override it, or customize the prompt, then you
# should put your overrides in either 
# ~/.bashrc_username or ~/.remote-shell/bashrc_username.sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Adds support for per-user git config files.
source "$DIR/git-inject-custom-config.sh"
# Adds support for the git prompt
source "$DIR/phpish-git/git-prompt.sh"

# Prompt customisations. There are many environment
# variables you can use to customize the prompt. 
# For a complete list see 
# https://github.com/JeremySkinner/remote-shell/wiki/Environment-Variables
export GIT_PROMPT_ShowStatusWhenZero=0

# Loads the git prompt
export PROMPT_COMMAND='git-prompt'