# This contains common shell utilities used by all users
# This file is automatically generated and should not be modified

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$DIR/git-inject-custom-config.sh"