# This contains common shell utilities used by all users
# This file is automatically generated and should not be modified

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Adds support for per-user git config files.
source "$DIR/git-inject-custom-config.sh"

# Adds support for git prompt.
export PROMPT_COMMAND=gitPrompt

gitPrompt () {
    php "$DIR/phpish-git/git-prompt.php"
}